dependencies:
  - all:
    - head-branch: '^update/'
    - changed-files:
      - all-globs-to-any-file: '**/build.sbt'

docs:
  - changed-files:
    - any-glob-to-any-file: ['docs/**', 'website/**', '**/*.md']

sbt-scalac-profiling:
  - changed-files:
    - any-glob-to-any-file: 'sbt-plugin/**'

scalac-profiling:
  - changed-files:
    - any-glob-to-any-file: ['external/**', 'integrations/**', 'profiledb/**', 'plugin/**']

behind-the-scenes:
  - all:
    - changed-files:
      - any-globs-to-all-files: '!**/build.sbt'
      - any-globs-to-all-files: '!docs/**'
      - any-globs-to-all-files: '!website/**'
      - any-globs-to-all-files: '!**/*.md'
      - any-globs-to-all-files: '!sbt-plugin/**'
      - any-globs-to-all-files: '!external/**'
      - any-globs-to-all-files: '!integrations/**'
      - any-globs-to-all-files: '!profiledb/**'
      - any-globs-to-all-files: '!plugin/**'
