matrix:
  SBT_RUN:
    - sbt "plugin/test" "profilingSbtPlugin/scripted"
    - sbt "integrations/testOnly circe integration monocle better-files"
    - sbt "show {file:/drone/src/github.com/scalacenter/scalac-profiling/scalac/}compiler/scalaVersion" "showScalaInstances" "integrations/testOnly scalatest scalac"

clone:
  git:
    image: plugins/git
    tags: true
    recursive: true
    depth: 50
    submodule_update_remote: true
    submodule_override:
      scalac: https://github.com/scalacenter/scala.git
      vscode-scala: https://github.com/scalacenter/vscode-scala-profiledb.git
      sbt-plugin/src/sbt-test/external-projects/circe: https://github.com/jvican/circe.git

pipeline:
  restore_cache:
    image: appleboy/drone-sftp-cache
    secrets: [ sftp_cache_username, sftp_cache_private_key, sftp_cache_server, sftp_cache_path ]
    restore: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier
      - /drone/.sbt

  build:
    image: scalaplatform/scala:2.0
    when:
      branch: master
    commands:
      - git log | head -n 20
      - rm -rf /root/.coursier
      - ln -s /drone/.coursier /root/.coursier
      - ${SBT_RUN}
      - ./bin/clean-cache.sh

  rebuild_cache:
    image: appleboy/drone-sftp-cache
    secrets: [ sftp_cache_username, sftp_cache_private_key, sftp_cache_server, sftp_cache_path ]
    rebuild: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier
      - /drone/.sbt
