matrix:
  SBT_RUN:
    - sbt "plugin/test" "^^0.13.16 profilingSbtPlugin/scripted" "^^1.0.4 profilingSbtPlugin/scripted"
    - sbt "showScalaInstances" "integrations/testOnly circe integration monocle better-files scalac"
    - sbt "showScalaInstances" "integrations/testOnly scalatest shapeless"

clone:
  git:
    image: plugins/git
    tags: true
    recursive: true
    depth: 50
    submodule_override:
      scalac: https://github.com/scalacenter/scala.git
      vscode-scala: https://github.com/scalacenter/vscode-scala-profiledb.git
      sbt-plugin/src/sbt-test/external-projects/circe: https://github.com/jvican/circe.git

pipeline:
  restore_cache:
    image: appleboy/drone-sftp-cache
    secrets: [ sftp_cache_username, sftp_cache_private_key, sftp_cache_server, sftp_cache_path ]
    restore: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier
      - /drone/.sbt

  build:
    image: scalaplatform/scala:2.1
    when:
      branch: master
    commands:
      - git log | head -n 20
      - ${SBT_RUN}
      - ./bin/clean-cache.sh

  rebuild_cache:
    image: appleboy/drone-sftp-cache
    secrets: [ sftp_cache_username, sftp_cache_private_key, sftp_cache_server, sftp_cache_path ]
    rebuild: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier
      - /drone/.sbt
