name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - integration-test
jobs:
  test:
    name: ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - sbt "plugin/test" "^^0.13.17 profilingSbtPlugin/scripted" "^^1.1.1 profilingSbtPlugin/scripted compiler-profiling/*"
          - sbt "showScalaInstances" "integrations/testOnly circe integration monocle better-files scalac"
          - sbt "showScalaInstances" "integrations/testOnly scalatest shapeless"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: olafurpg/setup-scala@v13
      - uses: coursier/cache-action@v5
      - run: ${{ matrix.command }}
