name: CI
on:
  push:
    tags: [v*]
    branches: ['**', '!update/**', '!pr/**']
  pull_request:
    branches: ['**', '!update/**', '!pr/**']

jobs:
  test:
    name: ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - sbt "+plugin/test" "profilingSbtPlugin/scripted compiler-profiling/scripted"
          - sbt "showScalaInstances" "integrations/testOnly integration better-files wartremover"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: olafurpg/setup-scala@v13
      - uses: coursier/cache-action@v5
      - run: ${{ matrix.command }}
