name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command: # https://github.com/sbt/sbt/issues/2901
          - sbt "plugin/test" "profilingSbtPlugin/scripted compiler-profiling/*"
          - sbt "showScalaInstances" "+integrations/testOnly circe integration better-files monocle"
            # - sbt "showScalaInstances" "+integrations/testOnly scalatest shapeless"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: olafurpg/setup-scala@v13
      - uses: coursier/cache-action@v5
      - run: ${{ matrix.command }}
