name: CI
on:
  push:
    tags: ["*"]
    branches: ['**', '!update/**', '!pr/**']
  pull_request:
    branches: ['**', '!update/**', '!pr/**']

jobs:
  scalafmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: olafurpg/setup-scala@v14
      - uses: coursier/cache-action@v6
      - name: Check formatting
        run: sbt -v "scalafmtSbtCheck" "scalafmtCheckAll"
  test:
    name: ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - sbt "+plugin/test" "profilingSbtPlugin/scripted compiler-profiling/scripted"
          - sbt "showScalaInstances" "integrations/testOnly integration better-files wartremover"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: olafurpg/setup-scala@v14
      - uses: coursier/cache-action@v6
      - run: ${{ matrix.command }}
