name: CI
on:
  push:
    tags: ["*"]
    branches: ['**', '!update/**', '!pr/**']
  pull_request:
    branches: ['**', '!update/**', '!pr/**']

jobs:
  scalafmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - name: Check formatting
        run: sbt -v "scalafmtSbtCheck" "scalafmtCheckAll"
  docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - run: sbt docs/run
  plugin-tests:
    name: Compiler and SBT plugin tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: coursier/cache-action@v6
      - name: Compiler plugin tests
        run: sbt -v "+plugin/test"
      - name: SBT plugin tests
        run: sbt -v "profilingSbtPlugin/scripted"
  intergration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: coursier/cache-action@v6
      - name: Running tests
        run: sbt -v "showScalaInstances" "integrations/testOnly integration better-files wartremover"
